version: "3.8"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-5}
      - OPENAI_FALLBACK_MODEL=${OPENAI_FALLBACK_MODEL:-gpt-4o-mini}
      - PUBLIC_BASE_URL=${PUBLIC_BASE_URL:-http://localhost:3000}
      - PROMPT_FILE=${PROMPT_FILE:-/app/AI_setting/system_prompt.md}


